import { CalendarioService } from '../services/data.service.js';
import { UI, escapeHtml } from '../core/ui.js';
import { Auth } from '../core/auth.js';
import { AuditService } from '../services/audit.service.js';

const MESES=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const DIAS=['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'];
const TIPOS=['inicio','examen','reunion','entrega','suspension','vacaciones','evento','fin'];
export async function renderCalendario(container){
 const puedeEditar=Auth.hasRole('admin'); const hoy=new Date(); let cursor=new Date(hoy.getFullYear(),hoy.getMonth(),1); let filtro='todos'; let eventos=await CalendarioService.todos();
 container.innerHTML=`<div class="page-head"><div><h1 class="page-title"><i class="fas fa-calendar-days"></i> Calendario escolar</h1><p class="page-sub">Agenda institucional, evaluaciones, reuniones y fechas clave del ciclo.</p></div>${puedeEditar?'<button class="btn btn-primary" id="nuevoEvento"><i class="fas fa-plus"></i> Nuevo evento</button>':''}</div><div class="filter-bar"><button class="btn btn-secondary btn-sm" id="prev"><i class="fas fa-chevron-left"></i></button><button class="btn btn-secondary btn-sm" id="hoy">Hoy</button><button class="btn btn-secondary btn-sm" id="next"><i class="fas fa-chevron-right"></i></button><strong id="monthLabel" style="min-width:170px"></strong><select class="select" id="tipoFiltro" style="margin-left:auto;max-width:220px"><option value="todos">Todos los eventos</option>${TIPOS.map(t=>`<option value="${t}">${cap(t)}</option>`).join('')}</select></div><div class="calendar-shell"><div class="card"><div class="calendar-grid-wrap"><div class="calendar-grid" id="calendar"></div></div></div><aside class="card"><div class="card-header"><h3 class="card-title">Agenda del mes</h3></div><div id="agenda"></div></aside></div>`;
 const render=()=>{const y=cursor.getFullYear(),m=cursor.getMonth();container.querySelector('#monthLabel').textContent=`${MESES[m]} ${y}`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());const shown=filtro==='todos'?eventos:eventos.filter(e=>e.tipo===filtro);let html=DIAS.map(d=>`<div class="calendar-weekday">${d}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=localISO(d),inMonth=d.getMonth()===m,isToday=localISO(hoy)===iso,ev=shown.filter(e=>e.fecha===iso);html+=`<div class="calendar-day ${inMonth?'':'is-muted'} ${isToday?'is-today':''}" data-day="${iso}"><div class="calendar-number">${d.getDate()}</div>${ev.slice(0,3).map(e=>`<button class="calendar-event" data-event="${e.id}" data-type="${escapeHtml(e.tipo||'inicio')}">${escapeHtml(e.titulo)}</button>`).join('')}${ev.length>3?`<small>+${ev.length-3} más</small>`:''}</div>`}container.querySelector('#calendar').innerHTML=html;const monthEvents=shown.filter(e=>{const d=new Date(e.fecha+'T12:00:00');return d.getFullYear()===y&&d.getMonth()===m}).sort((a,b)=>a.fecha.localeCompare(b.fecha));container.querySelector('#agenda').innerHTML=monthEvents.length?monthEvents.map(e=>`<button class="list-item" data-event="${e.id}" style="width:100%;text-align:left;background:none;cursor:pointer"><div style="width:42px;text-align:center"><strong>${Number(e.fecha.slice(-2))}</strong><small style="display:block;color:var(--text-muted)">${MESES[m].slice(0,3)}</small></div><div><div class="list-item-title">${escapeHtml(e.titulo)}</div><div class="list-item-desc">${cap(e.tipo||'evento')}</div></div></button>`).join(''):'<div class="empty"><i class="fas fa-calendar-xmark"></i><h4>Sin eventos</h4><p>No hay eventos con este filtro.</p></div>';bindCells();};
 function bindCells(){container.querySelectorAll('[data-day]').forEach(el=>el.addEventListener('dblclick',()=>puedeEditar&&editEvent(null,el.dataset.day)));container.querySelectorAll('[data-event]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();const item=eventos.find(x=>x.id===Number(el.dataset.event));editEvent(item)}));}
 function editEvent(item,fecha=''){if(!puedeEditar&&item){UI.modal({title:item.titulo,body:`<p>${escapeHtml(item.descripcion||'Sin descripción')}</p><p class="text-muted">${item.fecha} · ${cap(item.tipo||'evento')}</p>`});return}const {overlay,close}=UI.modal({title:item?'Editar evento':'Nuevo evento',body:`<form id="eventForm"><div class="form-group"><label class="label">Título</label><input class="input" name="titulo" required maxlength="80" value="${escapeHtml(item?.titulo||'')}"></div><div class="form-grid"><div class="form-group"><label class="label">Fecha</label><input class="input" type="date" name="fecha" required value="${item?.fecha||fecha||localISO(hoy)}"></div><div class="form-group"><label class="label">Tipo</label><select class="select" name="tipo">${TIPOS.map(t=>`<option value="${t}" ${item?.tipo===t?'selected':''}>${cap(t)}</option>`).join('')}</select></div></div><div class="form-group"><label class="label">Descripción</label><textarea class="input" name="descripcion" rows="3">${escapeHtml(item?.descripcion||'')}</textarea></div><div style="display:flex;justify-content:${item?'space-between':'flex-end'};gap:8px;margin-top:18px">${item?'<button type="button" class="btn btn-danger" id="deleteEvent">Eliminar</button>':''}<button class="btn btn-primary">Guardar evento</button></div></form>`});const form=overlay.querySelector('#eventForm');form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));if(item){await CalendarioService.actualizar(item.id,data);AuditService.log('actualizó','evento',data.titulo)}else{await CalendarioService.crear(data);AuditService.log('creó','evento',data.titulo)}eventos=await CalendarioService.todos();close();UI.toast('Evento guardado','success');render()};overlay.querySelector('#deleteEvent')?.addEventListener('click',async()=>{if(await UI.confirm({title:'Eliminar evento',message:'Esta acción quitará el evento del calendario.',confirmText:'Eliminar',danger:true})){await CalendarioService.eliminar(item.id);AuditService.log('eliminó','evento',item.titulo);eventos=await CalendarioService.todos();close();render()}})}
 container.querySelector('#prev').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);render()};container.querySelector('#next').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);render()};container.querySelector('#hoy').onclick=()=>{cursor=new Date(hoy.getFullYear(),hoy.getMonth(),1);render()};container.querySelector('#tipoFiltro').onchange=e=>{filtro=e.target.value;render()};container.querySelector('#nuevoEvento')?.addEventListener('click',()=>editEvent(null));render();
}
const cap=s=>s.charAt(0).toUpperCase()+s.slice(1);const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
