import { AlumnosService, ProfesoresService, GruposService, MateriasService, HorariosService, CalificacionesService } from '../services/data.service.js';
import { Auth, ROLES } from '../core/auth.js';
import { escapeHtml } from '../core/ui.js';

const icon={alumno:'fa-user-graduate',profesor:'fa-chalkboard-user',grupo:'fa-users',materia:'fa-book-open',pagina:'fa-arrow-right'};
const ROLE_PAGES={
 [ROLES.ADMIN]:[['inicio','Inicio'],['alumnos','Alumnos'],['profesores','Profesores'],['grupos','Grupos'],['materias','Materias'],['inscripciones','Inscripciones'],['calificaciones','Calificaciones'],['asistencia','Asistencia'],['horarios','Horarios'],['kardex','Kárdex'],['avisos','Avisos'],['notificaciones','Notificaciones'],['calendario','Calendario'],['reportes','Reportes'],['auditoria','Auditoría'],['usuarios','Usuarios'],['configuracion','Configuración'],['mi-perfil','Mi perfil'],['ayuda','Ayuda']],
 [ROLES.PROFESOR]:[['inicio','Inicio'],['mi-perfil','Mi perfil docente'],['mis-grupos','Mis grupos'],['horarios','Mi horario'],['calificaciones','Calificaciones'],['asistencia','Asistencia'],['avisos','Avisos'],['notificaciones','Notificaciones'],['ayuda','Ayuda']],
 [ROLES.ALUMNO]:[['inicio','Inicio'],['mi-kardex','Mi Kárdex'],['mis-calificaciones','Mis calificaciones'],['mi-horario','Mi horario'],['mi-asistencia','Mi asistencia'],['boleta','Mi boleta'],['tramites','Mis trámites'],['documentos','Mis documentos'],['avisos','Avisos'],['notificaciones','Notificaciones'],['mi-perfil','Mi perfil'],['ayuda','Ayuda']]
};
export function initGlobalSearch(input){
 if(!input)return; const panel=document.createElement('div'); panel.className='command-palette'; panel.hidden=true; panel.innerHTML='<div class="command-results"></div><div class="command-help"><span>↑↓ navegar</span><span>Enter abrir</span><span>Esc cerrar</span></div>'; document.body.append(panel);
 let results=[],active=0,timer; const pages=()=>ROLE_PAGES[Auth.user?.rol]||[['inicio','Inicio']]; const close=()=>{panel.hidden=true;input.setAttribute('aria-expanded','false')}; const open=()=>{panel.hidden=false;input.setAttribute('aria-expanded','true')};
 const draw=()=>{const wrap=panel.querySelector('.command-results');if(!results.length){wrap.innerHTML='<div class="command-empty">No hay resultados disponibles para tu cuenta.</div>';return;}wrap.innerHTML=results.map((r,i)=>`<button class="command-item ${i===active?'active':''}" data-i="${i}"><span class="command-icon"><i class="fas ${icon[r.type]||'fa-arrow-right'}"></i></span><span><strong>${escapeHtml(r.title)}</strong><small>${escapeHtml(r.subtitle||r.type)}</small></span><kbd>↵</kbd></button>`).join('');wrap.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>go(Number(b.dataset.i)));};
 const go=i=>{const r=results[i];if(!r||!Auth.can(r.route))return;if(r.type==='alumno'&&Auth.hasRole(ROLES.ADMIN))sessionStorage.setItem('busquedaGlobal',r.title);location.hash=`#/${r.route}`;close();input.value='';};
 async function search(q){q=q.trim().toLowerCase();const has=s=>String(s||'').toLowerCase().includes(q);const role=Auth.user?.rol,allowedPages=pages();if(!q){results=allowedPages.slice(0,8).map(([route,title])=>({type:'pagina',title,subtitle:'Ir a módulo',route}));active=0;draw();open();return;}const pageResults=allowedPages.filter(([,n])=>has(n)).map(([route,title])=>({type:'pagina',title,subtitle:'Ir a módulo',route}));
  if(role===ROLES.ALUMNO){const filas=await CalificacionesService.porAlumno(Auth.user.alumnoId||1);const materias=filas.map(f=>f.materia).filter(Boolean);results=[...materias.filter(m=>has(`${m.nombre} ${m.clave}`)).slice(0,6).map(m=>({type:'materia',title:m.nombre,subtitle:`Tu materia · ${m.clave}`,route:'mis-calificaciones'})),...pageResults].slice(0,12);}
  else if(role===ROLES.PROFESOR){const pid=Auth.user.profesorId;const [horarios,grupos,materias,alumnos]=await Promise.all([HorariosService.porProfesor(pid),GruposService.todos(),MateriasService.todos(),AlumnosService.todos()]);const gids=[...new Set(horarios.map(h=>Number(h.grupoId)))],mids=[...new Set(horarios.map(h=>Number(h.materiaId)))];results=[...grupos.filter(g=>gids.includes(Number(g.id))&&has(g.nombre)).slice(0,4).map(g=>({type:'grupo',title:g.nombre,subtitle:'Grupo asignado',route:'mis-grupos'})),...materias.filter(m=>mids.includes(Number(m.id))&&has(`${m.nombre} ${m.clave}`)).slice(0,4).map(m=>({type:'materia',title:m.nombre,subtitle:`Materia asignada · ${m.clave}`,route:'calificaciones'})),...alumnos.filter(a=>gids.includes(Number(a.grupoId))&&has(`${a.nombre} ${a.apellidos} ${a.matricula}`)).slice(0,4).map(a=>({type:'alumno',title:`${a.nombre} ${a.apellidos}`,subtitle:`Alumno de tus grupos · ${a.matricula}`,route:'calificaciones'})),...pageResults].slice(0,12);}
  else{const [aa,pp,gg,mm]=await Promise.all([AlumnosService.todos(),ProfesoresService.todos(),GruposService.todos(),MateriasService.todos()]);results=[...aa.filter(a=>has(`${a.nombre} ${a.apellidos} ${a.matricula}`)).slice(0,5).map(a=>({type:'alumno',title:`${a.nombre} ${a.apellidos}`,subtitle:`Alumno · ${a.matricula} · ${a.grado}`,route:'alumnos'})),...pp.filter(p=>has(`${p.nombre} ${p.apellidos} ${p.area}`)).slice(0,4).map(p=>({type:'profesor',title:`${p.nombre} ${p.apellidos}`,subtitle:`Profesor · ${p.area}`,route:'profesores'})),...gg.filter(g=>has(g.nombre)).slice(0,3).map(g=>({type:'grupo',title:g.nombre,subtitle:`Grupo · Aula ${g.aula||'—'}`,route:'grupos'})),...mm.filter(m=>has(`${m.nombre} ${m.clave}`)).slice(0,3).map(m=>({type:'materia',title:m.nombre,subtitle:`Materia · ${m.clave}`,route:'materias'})),...pageResults].slice(0,12);}active=0;draw();open();}
 input.addEventListener('focus',()=>search(input.value));input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value),120)});input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();active=Math.min(active+1,results.length-1);draw()}if(e.key==='ArrowUp'){e.preventDefault();active=Math.max(active-1,0);draw()}if(e.key==='Enter'&&results.length){e.preventDefault();go(active)}if(e.key==='Escape')close()});document.addEventListener('click',e=>{if(e.target!==input&&!panel.contains(e.target))close()});
}
